// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgrVlg_SrdI6X3hTqVYi3QsmFkNJRzqRo',
    appId: '1:981408961624:web:2f1c13cf4583d55c29a62d',
    messagingSenderId: '981408961624',
    projectId: 'mybookstash-690b7',
    authDomain: 'mybookstash-690b7.firebaseapp.com',
    storageBucket: 'mybookstash-690b7.appspot.com',
    measurementId: 'G-1QS56KM9TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98QXNezE8A7YC2wLdndgIkhf1r4ApFmI',
    appId: '1:981408961624:android:238540070a933c5529a62d',
    messagingSenderId: '981408961624',
    projectId: 'mybookstash-690b7',
    storageBucket: 'mybookstash-690b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTPvSAk3qSANZu1lGZNB4XoyqSdWNc9k',
    appId: '1:981408961624:ios:9d275eb1ad29a27329a62d',
    messagingSenderId: '981408961624',
    projectId: 'mybookstash-690b7',
    storageBucket: 'mybookstash-690b7.appspot.com',
    iosBundleId: 'com.example.booksStashh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFTPvSAk3qSANZu1lGZNB4XoyqSdWNc9k',
    appId: '1:981408961624:ios:9d275eb1ad29a27329a62d',
    messagingSenderId: '981408961624',
    projectId: 'mybookstash-690b7',
    storageBucket: 'mybookstash-690b7.appspot.com',
    iosBundleId: 'com.example.booksStashh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgrVlg_SrdI6X3hTqVYi3QsmFkNJRzqRo',
    appId: '1:981408961624:web:e5873ff425025cf529a62d',
    messagingSenderId: '981408961624',
    projectId: 'mybookstash-690b7',
    authDomain: 'mybookstash-690b7.firebaseapp.com',
    storageBucket: 'mybookstash-690b7.appspot.com',
    measurementId: 'G-VFKLVHDQVE',
  );
}
